Repository fullstacktf/myment-docs, pull requests merged in 2019-07, with the labels that each got.

#2 Create SECURITY.md
  SECURITY.md
Labels: bug

#1 Adding gitbook boilerplate to develop docs
  .gitignore
  README.md
  SUMMARY.md
  front-docs/LANDING_PAGE.md
  src/index.js
Labels: documentation

#8 added the unlgoed use path of interaction
  SUMMARY.md
  front-docs/FRONTEND_STRUCTURE.md
  front-docs/LANDING_PAGE.md
  front-docs/UNLOGED_USE.md
  package-lock.json
Labels: Priority: Medium

#9 Provide news functionality
  README.md
  SUMMARY.md
  book.json
  front-docs/USE_CASES.md
  package-lock.json
  package.json
  speech-docs/INTRODUCTION.md
  travelstats.png
  traveltrend.jpg
Labels: enhancement, feature
